site_name: Weighted Correlation Velocimetry
site_url: https://<user>.github.io/weighted-correlation-velocimetry/
repo_url: https://github.com/<user>/weighted-correlation-velocimetry

theme:
  name: material

nav:
  - Home: index.md
  - Theory: theory.md
  - Implementation: implementation.md
  - Usage: usage.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
